# Generated by Django 4.1.7 on 2023-04-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(  # created table for storeitemdes class and its attributes
            name='StoreItemDes',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.IntegerField()),
                ('image', models.ImageField(upload_to='pics')),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=50)),
            ],
        ),
    ]
